services:
  - type: web
    name: simplifica-financas
    env: python
    region: oregon
    plan: free
    branch: main

    # ðŸ‘‡ ISSO Ã© o que realmente funciona
    pythonVersion: 3.11.9

    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app

    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: simplifica-financas-db
          property: connectionString
      - key: FLASK_ENV
        value: production
      - key: FLASK_DEBUG
        value: "False"

databases:
  - name: simplifica-financas-db
    databaseName: gestao_financeira
    user: admin_financas
    region: oregon
    plan: free
    ipAllowList: []
