services:
  - type: web
    name: simplifica-financas
    env: python
    region: virginia   # Virginia (US East)
    plan: free
    branch: main

    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app

    envVars:
      - key: SECRET_KEY
        generateValue: true

      - key: DATABASE_URL
        sync: false   # vamos definir manualmente no dashboard

      - key: FLASK_DEBUG
        value: "False"
